---

- name: --Install Prometheus--
  hosts: prometheus
  become: yes
  vars_files:
    - vars/main.yml

  tasks:

    - name: create prometheus user
      user:
        name: prometheus
        shell: /usr/sbin/nologin

    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /usr/local/bin/prometheus
        - /var/lib/prometheus

    - name: download prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-arm64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: extract prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /usr/local/bin/prometheus
        remote_src: yes

    - name: create systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=prometheus server
          Wants=network-oniline.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          Restart=on-failure
          ExecStart=/usr/local/bin/prometheus/prometheus-3.10.0.linux-arm64/prometheus \
            --config.file=/usr/local/bin/prometheus/prometheus-3.10.0.linux-arm64/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus
            --web.listen-address=0.0.0.0:9090

          Restart=on-failure
          RestartSec=5s
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target

    - name: test alert
      copy:
        dest: /usr/local/bin/prometheus/prometheus-3.10.0.linux-arm64/alerts.yml
        content: |
          groups:
            - name: cpu-alert
              rules:
                - alert: "CPU ALARM!!!"
                  expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
                  for: 1m
                  labels:
                    severity: warning
                  annotations:
                    summary: "I kinda already said everything but yes cpu usage is over 80% on Ubuntu."
                    description: "ALARM!! UBUNTU CPU USAGE TOO HIGH! WATCH OUT NOO!!"
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: configure prometheus.yml
      template:
        src: prometheus.yml.j2
        dest: /usr/local/bin/prometheus/prometheus-3.10.0.linux-arm64/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: restart systemd
      command: systemctl daemon-reload

    - name: restart prometheus
      service:
        name: prometheus
        state: restarted

    - name: enable prometheus
      service:
        name: prometheus
        enabled: yes
        state: started

- name: --install node exporter--
  hosts: nodex
  become: yes

  tasks:

    - name: create nodex user
      user:
        name: nodex
        shell: /usr/sbin/nologin

    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: nodex
        group: nodex
      loop:
        - /usr/local/bin/node_exporter
        - /var/lib/node_exporter

    - name: download nodex
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-1.10.2.linux-arm64.tar.gz
        dest: /tmp

    - name: extract nodex
      unarchive:
        src: /tmp/node_exporter-1.10.2.linux-arm64.tar.gz
        dest: /usr/local/bin/node_exporter
        remote_src: yes

    - name: create systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=node_exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=nodex
          Group=nodex
          Type=simple
          ExecStart=/usr/local/bin/node_exporter/node_exporter-1.10.2.linux-arm64/node_exporter \
            --collector.systemd
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: restart systemd
      command: systemctl daemon-reload

    - name: start nodex
      systemd:
        name: node_exporter
        enabled: yes
        state: started

- name: --install alert manager--
  hosts: prometheus
  become: yes
  vars_files:
    - vars/main.yml

  tasks:

    - name: create alert user
      user:
        name: alerti
        shell: /usr/sbin/nologin

    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: alerti
        group: alerti
      loop:
        - /usr/local/bin/alertmanager
        - /var/lib/alertmanager

    - name: download alerti
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.31.0/alertmanager-0.31.0.linux-arm64.tar.gz
        dest: /tmp/alertmanager.tar.gz

    - name: extract alerti
      unarchive:
        src: /tmp/alertmanager.tar.gz
        dest: /usr/local/bin/alertmanager
        remote_src: yes

    - name: create alerti.yml
      copy:
        dest: /usr/local/bin/alertmanager/alertmanager-0.31.0.linux-arm64/alerti.yml
        content: |
          global:
            resolve_timeout: 5m

          route:
            receiver: "msteams"

          receivers:
            - name: "msteams"
              msteams_configs:
                - webhook_url: "{{ webhook_url }}"
                  send_resolved: true
                  title: test

    - name: create systemd service
      copy:
        dest: /etc/systemd/system/alertmanager.service
        content: |
          [Unit]
          Description=alertmanager
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=alerti
          Group=alerti
          Type=simple
          WorkingDirectory=/usr/local/bin/alertmanager/
          ExecStart=/usr/local/bin/alertmanager/alertmanager-0.31.0.linux-arm64/alertmanager \
            --config.file=/usr/local/bin/alertmanager/alertmanager-0.31.0.linux-arm64/alerti.yml \
            --web.external-url http://0.0.0.0:9093

          [Install]
          WantedBy=multi-user.target

    - name: restart systemd
      command: systemctl daemon-reload

    - name: restart alertmanager
      service:
        name: alertmanager
        state: restarted

    - name: start alterti
      systemd:
        name: alertmanager
        enabled: yes
        state: started
